---
title: "script"
author: "APB"
date: "4/30/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(echo = TRUE)
```


#Load/Clean data
```{r load_data, include=FALSE}
feed_data<-read.csv("data/feeding_data_3.28.21.csv", header=T)

po<-read.csv("data/4_Day_PO.csv", header = T) #Corrected_Change is the Active PO per sample (8 ind. per sample)

growth<-read.csv("data/growth_data_3.28.21.csv", header=T)

life<-read.csv("data/life_data_3.28.21.csv", header =T)

```


#Calculate feeding rates
```{r animal_feed_rates, include = FALSE}
#calculate the mean of the controls for each plate
summary_data <- feed_data %>%
  group_by(Plate_Control) %>%
  mutate(control_mean = mean(Control_Flour_Reading, na.rm = T)) %>%
  select(Plate_Control, control_mean) %>%
  distinct() %>% as.data.frame()

#remove extra row
summary_data  <- summary_data[!(summary_data$Plate_Control == ""),]

#match control mean with plate treatment
map = setNames(summary_data$control_mean,summary_data$Plate_Control)
feed_data$control_mean <- map[as.character(feed_data$Plate_Treatment)]

#volume, mL
v = 10

#time, hours
t = 9

##difference in feeding compared to control
k=feed_data$control_mean/feed_data$Flourometry_Reading

##calculate feeding rate (Sarnelle and Wilson)
feed_data$fr_sw <- log(k) * (v/t)

#calculate mean feeding rate per animal (keep rate > 0)
animal_mean <- feed_data %>%
  #keep fr_sw values > 0
  #filter(fr_sw > 0) %>% #this removes 64 animals...
  #group based on these variables
  group_by(Time_treatment, Age, Animal, Exposed.Control) %>%
  #means based on groups above
  summarise(fr_sw = mean(fr_sw, na.rm=TRUE)) 

```


#Merge dataframes
```{r combine_dataframes, include=FALSE}
#combine feeding rates with life history data 
merge(animal_mean, life, by=c("Age", "Time_treatment", "Animal", "Exposed.Control"), keep=TRUE) %>%
  mutate(id = paste(Age,
                    Time_treatment,
                    Animal,
                    Exposed.Control, 
                    sep = "_")) %>%
           as.data.frame()->all.data


#create id for growth data 
growth %>%
  mutate(id = paste(Age,
                    Time_treatment,
                    Animal,
                    Exposed.Control, 
                    sep = "_")) %>%
           as.data.frame()->growth
```


#Exploratory Plots
```{r feeding_rate_plot, echo=FALSE}
all.data %>%
  filter(Sex == "F")%>%
  ggplot()+
  geom_boxplot(aes(x=as.factor(Age), y=fr_sw, color=Time_treatment))+
  scale_color_manual(values=c("goldenrod2", "darkblue"))+
  facet_grid(.~Exposed.Control)+
  theme_bw()

all.data %>%
  filter(Sex == "F")%>%
  ggplot()+
  geom_jitter(aes(x=Time_treatment, y=fr_sw, color=Exposed.Control))+
  scale_color_manual(values=c("black", "limegreen"))+
  facet_grid(.~Age)+
  theme_bw()

```

```{r po_plots, echo=FALSE}
po %>%
  ggplot()+
  geom_point(aes(x=Hours_from_Start, y =Corrected_Change, color=Time_treatment))+
  scale_color_manual(values=c("goldenrod2", "darkblue"))+
  geom_smooth(aes(x=Hours_from_Start, y =Corrected_Change), color="black", span=1)+
  theme_bw()

po %>%
  ggplot(aes(x=Age, y = Corrected_Change, color=Phase))+
  geom_point()+
  geom_smooth(method="lm")

po %>%
  ggplot(aes(x=Age, y = Corrected_Change/8, color=Phase))+
  geom_point()+
  geom_smooth(method="lm")

```

```{r growth_plots, echo=FALSE}
growth %>%
  filter(Age == 6) %>%
  ggplot(aes(x=days_post_exposure, y=Length_at_exposure_mm, color=as.factor(Animal)))+
  geom_point()+
  geom_line()+
  facet_grid(Time_treatment~.)

growth %>%
  filter(Age == 7) %>%
  ggplot(aes(x=days_post_exposure, y=Length_at_exposure_mm, color=as.factor(Animal)))+
  geom_point()+
  geom_line()+
  facet_grid(Time_treatment~.)

growth %>%
  filter(Age == 8) %>%
  ggplot(aes(x=days_post_exposure, y=Length_at_exposure_mm, color=as.factor(Animal)))+
  geom_point()+
  geom_line()+
  facet_grid(Time_treatment~.)

growth %>%
  filter(Age == 9) %>%
  ggplot(aes(x=days_post_exposure, y=Length_at_exposure_mm, color=as.factor(Animal)))+
  geom_point()+
  geom_line()+
  facet_grid(Time_treatment~.)

#lag and lead

```


```{r infection_plot, echo=FALSE}

# infection prevalence
all.data %>%
  filter(Time_treatment == "Exposed" | Sex == "F") %>%
  ggplot(aes(x=Age, y=infected, color=Time_treatment))+
  scale_color_manual(values=c("goldenrod2", "darkblue"))+
  geom_jitter(width = .1, height = .1)+
  geom_smooth(method="lm")+
  scale_y_continuous(limits=c(-.1,1))+
  scale_x_continuous(breaks=c(6,7,8,9))+
  theme_bw()


#infection intensity
life %>%
  filter(Time_treatment == "Exposed"| Sex == "F") %>%
  ggplot(aes(x=Age, y=spore_counts, color=Time_treatment))+
  scale_color_manual(values=c("goldenrod2", "darkblue"))+
  #geom_jitter(width=.25)+
  geom_point()+
  geom_smooth(method="lm")+
  theme_bw()

```


```{r offsrping_plots, echo=FALSE}

#total offspring
all.data %>%
  filter(Sex == "F") %>%
  #filter(infected != "NA") %>%     #removes controls
  ggplot(aes(x=Time_treatment, y=total_offspring, fill=as.factor(infected)))+
  geom_boxplot()+
  facet_grid(~Age)


#age at first clutch
all.data %>% 
  filter(Sex == "F") %>%
  #filter(infected != "NA") %>%     #removes controls
  ggplot(aes(x=Time_treatment, y=age_at_first_clutch, fill=as.factor(infected)))+
  geom_boxplot()+
  facet_grid(~Age)

```


#Stats
```{r po}

#Does PO differ across a day (Resting = Light hours, Active = dark hours) and across ages? 
summary(po_model<-glm(Corrected_Change ~ Phase*as.factor(Age), data=po))
plot(po_model)

newdata<-expand.grid(Phase=c("Active", "Resting"), Age = 6:9)
newdata$preds<-predict(po_model, newdata=newdata)

newdata %>%
  ggplot()+
  geom_line(aes(x=Age, y=preds, color=Phase))+
  geom_point(po, mapping=aes(x=Age, y=Corrected_Change, color=Phase), alpha = 0.5)
```



```{r infection_prevalence}
prev <- all.data %>%
  filter(Exposed.Control == "Exposed") %>%
  group_by(Age, Time_treatment) %>%
  summarise(inf = sum(infected, na.rm=T),
            n = length(infected),
            prev = inf/n)

#Does infection prevalence increase with age and night exposure?
summary(inf_model<-glm(infected ~ as.factor(Age)+Time_treatment, 
               family = binomial, 
               data=filter(all.data, Exposed.Control == "Exposed")))

```


```{r}

#Does infection intensity increase with Age and night exposure?
summary(spore_model<-glm(spore_counts ~ as.factor(Age) * Time_treatment, family = poisson(), data=filter(all.data, infected == 1)))
plot(spore_model)


```

